void printresults10times() {

    int nrand = 0, nrand2 = 0, propx = 0, nranda = 0, nrandb = 0, nranda2 = 0, nrandb2 = 0,
    fact1_1a = 0, fact1_1b = 0, fact1_2a = 0, fact1_2b = 0, fact2_1a = 0, fact2_1b = 0,
    fact2_2a = 0, fact2_2b = 0, fact2_3a = 0, fact2_3b = 0, fact3_1a = 0, fact3_1b = 0,
    fact3_2a = 0, fact3_2b = 0, fact3_3a = 0, fact3_3b = 0, fact3_4a = 0, fact3_4b = 0,
    factx_1a = 0, factx_1b = 0, factx_2a = 0, factx_2b = 0,
    fact1_1an = 0, fact1_1bn = 0, fact1_2an = 0, fact1_2bn = 0, fact2_1an = 0, fact2_1bn = 0,
    fact2_2an = 0, fact2_2bn = 0, fact2_3an = 0, fact2_3bn = 0, fact3_1an = 0, fact3_1bn = 0,
    fact3_2an = 0, fact3_2bn = 0, fact3_3an = 0, fact3_3bn = 0, fact3_4an = 0, fact3_4bn = 0,
    factx_1an = 0, factx_1bn = 0, factx_2an = 0, factx_2bn = 0,
    fact1_1a2 = 0, fact1_1b2 = 0, fact1_2a2 = 0, fact1_2b2 = 0, fact2_1a2 = 0, fact2_1b2 = 0,
    fact2_2a2 = 0, fact2_2b2 = 0, fact2_3a2 = 0, fact2_3b2 = 0, fact3_1a2 = 0, fact3_1b2 = 0,
    fact3_2a2 = 0, fact3_2b2 = 0, fact3_3a2 = 0, fact3_3b2 = 0, fact3_4a2 = 0, fact3_4b2 = 0,
    factx_1a2 = 0, factx_1b2 = 0, factx_2a2 = 0, factx_2b2 = 0,
    fact1_1an2 = 0, fact1_1bn2 = 0, fact1_2an2 = 0, fact1_2bn2 = 0, fact2_1an2 = 0, fact2_1bn2 = 0,
    fact2_2an2 = 0, fact2_2bn2 = 0, fact2_3an2 = 0, fact2_3bn2 = 0, fact3_1an2 = 0, fact3_1bn2 = 0,
    fact3_2an2 = 0, fact3_2bn2 = 0, fact3_3an2 = 0, fact3_3bn2 = 0, fact3_4an2 = 0, fact3_4bn2 = 0,
    factx_1an2 = 0, factx_1bn2 = 0, factx_2an2 = 0, factx_2bn2 = 0;

    if (FORM_REC10 == iFormSubmitted)
        nrand = iNrandRec;
    else
        nrand = iNrandUnrec;

    nrand = iNrandRec;        
    nrand2 = nrand * pow(10, iPower);
    iPower++;
    
    //printf(
        
    //printf("10 times: %d", iFormSubmitted); return;
    
/*    printf(
"                seed,"
"                iFormSubmitted, nrand, iPercent, nranda, nrandb,"
"                fact1_1a, fact1_1b, fact1_2a, fact1_2b, fact2_1a:<p>before<p>"
"%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d",
                seed,
                iFormSubmitted, nrand, iPercent, nranda, nrandb,
                fact1_1a, fact1_1b, fact1_2a, fact1_2b, fact2_1a);  */    

    //getseed_(&seed);
    simplerand2_(
                &seed,
                &iFormSubmitted, &nrand, &iPercent, &nranda, &nrandb,
                &fact1_1a, &fact1_1b, &fact1_2a, &fact1_2b, &fact2_1a, &fact2_1b,
                &fact2_2a, &fact2_2b, &fact2_3a, &fact2_3b, &fact3_1a, &fact3_1b,
                &fact3_2a, &fact3_2b, &fact3_3a, &fact3_3b, &fact3_4a, &fact3_4b,
                &factx_1a, &factx_1b, &factx_2a, &factx_2b,
                &fact1_1an, &fact1_1bn, &fact1_2an, &fact1_2bn, &fact2_1an, &fact2_1bn,
                &fact2_2an, &fact2_2bn, &fact2_3an, &fact2_3bn, &fact3_1an, &fact3_1bn,
                &fact3_2an, &fact3_2bn, &fact3_3an, &fact3_3bn, &fact3_4an, &fact3_4bn,
                &factx_1an, &factx_1bn, &factx_2an, &factx_2bn);

    simplerand2_(
                &seed,
                &iFormSubmitted, &nrand2, &iPercent, &nranda2, &nrandb2,
                &fact1_1a2, &fact1_1b2, &fact1_2a2, &fact1_2b2, &fact2_1a2, &fact2_1b2,
                &fact2_2a2, &fact2_2b2, &fact2_3a2, &fact2_3b2, &fact3_1a2, &fact3_1b2,
                &fact3_2a2, &fact3_2b2, &fact3_3a2, &fact3_3b2, &fact3_4a2, &fact3_4b2,
                &factx_1a2, &factx_1b2, &factx_2a2, &factx_2b2,
                &fact1_1an2, &fact1_1bn2, &fact1_2an2, &fact1_2bn2, &fact2_1an2, &fact2_1bn2,
                &fact2_2an2, &fact2_2bn2, &fact2_3an2, &fact2_3bn2, &fact3_1an2, &fact3_1bn2,
                &fact3_2an2, &fact3_2bn2, &fact3_3an2, &fact3_3bn2, &fact3_4an2, &fact3_4bn2,
                &factx_1an2, &factx_1bn2, &factx_2an2, &factx_2bn2);    

/*    printf("<p>after:<p>"
"%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d",
                seed,
                iFormSubmitted, nrand, iPercent, nranda, nrandb,
                fact1_1a, fact1_1b, fact1_2a, fact1_2b, fact2_1a);
    return;*/

    printf(
"<html>\n"
"<head>\n"
"<title>Randomisation results</title>\n"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\n"
"\n"
"<link rel=\"stylesheet\" href=\"cochrane.css\" type=\"text/css\">\n"
"<script language=\"Javascript\">\n"
"\n"
"function Show(ename) {	\n"
"	if(document.all) {\n"
"		for(var i = 0; i < document.all.length; ++i) {\n"
"			if(document.all[i].name == ename) {\n"
"				document.all[i].style.visibility ='visible';\n"
"			}\n"
"		}\n"
"	} else {\n"
"		var objs = document.getElementsByName(ename);\n"
"	   	for(var i = 0; i < objs.length; ++i) {  \n"
"			objs[i].style.visibility ='visible';\n"
"		}\n"
"	}\n"
"}\n"
"\n"
"function Show6() {\n"
"	Show(\"cond\");\n"
"}\n"
"\n"
"function Show5() {\n"
"	Show(\"age\");\n"
"	setTimeout(\"Show6()\", 1000);\n"
"}\n"
"\n"
"function Show4() {\n"
"	Show(\"sev\");\n"
"	setTimeout(\"Show5()\", 1000);\n"
"}\n"
"\n"
"function Show3() {\n"
"	Show(\"duration\");\n"
"	setTimeout(\"Show4()\", 1000);\n"
"}\n"
"\n"
"function Show2() {\n"
"	Show(\"heading\");\n"
"	setTimeout(\"Show3()\", 1000);\n"
"}\n"
"\n"
"function Show1() {\n"
"	setTimeout(\"Show2()\", 1000);\n"
"}\n"
"\n"
"</script>\n"
"</head>\n"
"\n"
"<body bgcolor=\"#FFFFFF\" onLoad=\"Show1()\">\n"
"<table border=1 cellspacing=0 cellpadding=10 width=750 bordercolor=\"#003366\" align=\"center\">\n"
"<tr><td>\n"
"  <table width=\"100%\">\n"
"    <tr><td>\n"
"      <table width=\"200\" border=\"0\" align=\"left\" cellpadding=\"3\">\n"
"        <tr>\n"
"          <td bgcolor=\"#EAEEF7\" width=\"100\" height=\"2\"> <div align=\"center\"><font size=\"-1\"><a href=\"http://www.jameslindlibrary.org/\" class=\"menubar\">Home</a></font></div></td>\n"
"          <td bgcolor=\"#EAEEF7\" height=\"2\" width=\"100\"> <div align=\"center\"><font size=\"-1\"><a href=\"http://www.jameslindlibrary.org/search\" class=\"menubar\">Search</a></font></div></td>\n"
"        </tr>\n"
"        <tr bgcolor=\"#EAEEF7\">\n"
"          <td colspan=\"2\"> <div align=\"center\"><b><font color=\"#003366\">jameslindlibrary.org</font></b></div></td>\n"
"        </tr>\n"
"      </table><br>\n"
"    </td></tr>\n"
"    <tr><td>\n"
"            <h4 align=\"center\">%d patients were randomised,<br>\n"
"              %d to treatment A, %d to treatment B:</h4>\n"
"            <h4 align=\"center\"><font size=\"-1\" color=\"#0000FF\">%d patients were \n"
"              randomised,<br>\n"
"              %d to treatment A, %d to treatment B:</font></h4>\n"
"    </td></tr>\n"
"  </table>\n"
"      <table width=\"80%\" align=\"center\" border=\"0\">\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td align=\"right\">Treatment A</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"n_trt_a1\">&nbsp;</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">Treatment B</td>\n"
"          <td name=\"n_trt_b1\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td align=\"right\">(total = %d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" id=\"hideable\" name=\"heading\" style=\"visibility:hidden\"><font color=\"#0000FF\">(total=%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">(total = %d)</td>\n"
"          <td name=\"n_trt_b2\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"heading\" style=\"visibility:hidden\">(total=%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td align=\"right\">number (%)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"n_trt_a3\"><font color=\"#0000FF\"></font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">number (%)</td>\n"
"          <td name=\"n_trt_b3\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\"></font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td><font color=\"#0000FF\"></font></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\"></font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td colspan=\"2\"><b>Duration of health problem</b></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td><font color=\"#0000FF\"></font></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\"></font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>Long term</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" id=\"hideable\" name=\"duration\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td name=\"n_dur_b1\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"duration\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>More recent</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"duration\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td name=\"n_dur_b2\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"duration\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td><font color=\"#0000FF\"></font></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\"></font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td colspan=\"2\"><b>Severity of health problem</b></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td><font color=\"#0000FF\"></font></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\"></font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>Mild</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"sev\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td name=\"n_sev_b1\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"sev\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>Moderate</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"sev\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td name=\"n_sev_b2\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"sev\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>Severe</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"sev\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td name=\"n_sev_b3\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"sev\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td><font color=\"#0000FF\"></font></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\"></font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td colspan=\"2\"><b>Age, in years</b></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td><font color=\"#0000FF\"></font></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\"></font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>Under 15</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"age\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td name=\"n_age_b1\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"age\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>15-34</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"age\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td name=\"n_age_b2\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"age\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>35-64</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"age\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td name=\"n_age_b3\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"age\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>65 &amp; older</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"age\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">&nbsp;%d (%d)</td>\n"
"          <td name=\"n_age_b4\">&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"age\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td><font color=\"#0000FF\"></font></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\"></font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td colspan=\"2\"><b>Condition: %s</b></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td><font color=\"#0000FF\"></font></td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td> \n"
"            <div align=\"right\"><font color=\"#0000FF\"></font></div>\n"
"          </td>\n"
"          <td>&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>Yes</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"cond\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\" name=\"n_cnd_b1\">&nbsp;</td>\n"
"          <td align=\"right\"> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"cond\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>No</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\" name=\"cond\" style=\"visibility:hidden\"><font color=\"#0000FF\">%d (%d)</font></td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">%d (%d)</td>\n"
"          <td align=\"right\" name=\"n_cnd_b2\">&nbsp;</td>\n"
"          <td align=\"right\"> \n"
"            <div align=\"right\"><font color=\"#0000FF\" name=\"cond\" style=\"visibility:hidden\">%d (%d)</font></div>\n"
"          </td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td>&nbsp;</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"          <td align=\"right\"> \n"
"            <div align=\"right\"></div>\n"
"          </td>\n"
"          <td align=\"right\">&nbsp;</td>\n"
"        </tr>\n"
"        <tr> \n"
"          <td>&nbsp;</td>\n"
"          <td colspan=\"9\"> \n"
"            <form name=\"form1\" >\n"
"              <input type=\"hidden\" name=\"seed\" value=\"%d\">\n"
"              <input type=\"hidden\" name=\"ftype\" value=\"%d\">\n"
"              <input type=\"hidden\" name=\"cat\" value=\"%s\">\n"
"			  <input type=\"hidden\" name=\"power\" value=\"%d\">\n"
"              <input type=\"hidden\" name=\"nrandrec\" value=\"%d\">\n"
"			  <input type=\"hidden\" name=\"perc\" value=\"%d\">\n"
"              <input type=\"submit\" name=\"Submit\" value=\"Make 10 times bigger\">\n"
"            </form>\n"
"          </td>\n"
"        </tr>\n"
"      </table>\n"
"<p><p><p><a href=\"%s\"><<< Back to beginning</a></td></tr></table>\n"
"</body>\n"
"</html>\n"

,

nrand,  nranda,  nrandb,
nrand2, nranda2, nrandb2,

nranda, nranda2, nrandb, nrandb2,

fact1_1an, fact1_1a, fact1_1an2, fact1_1a2, fact1_1bn, fact1_1b, fact1_1bn2, fact1_1b2,
fact1_2an, fact1_2a, fact1_2an2, fact1_2a2, fact1_2bn, fact1_2b, fact1_2bn2, fact1_2b2,

fact2_1an, fact2_1a, fact2_1an2, fact2_1a2, fact2_1bn, fact2_1b, fact2_1bn2, fact2_1b2,
fact2_2an, fact2_2a, fact2_2an2, fact2_2a2, fact2_2bn, fact2_2b, fact2_2bn2, fact2_2b2,
fact2_3an, fact2_3a, fact2_3an2, fact2_3a2, fact2_3bn, fact2_3b, fact2_3bn2, fact2_3b2,

fact3_1an, fact3_1a, fact3_1an2, fact3_1a2, fact3_1bn, fact3_1b, fact3_1bn2, fact3_1b2,
fact3_2an, fact3_2a, fact3_2an2, fact3_2a2, fact3_2bn, fact3_2b, fact3_2bn2, fact3_2b2,
fact3_3an, fact3_3a, fact3_3an2, fact3_3a2, fact3_3bn, fact3_3b, fact3_3bn2, fact3_3b2,
fact3_4an, fact3_4a, fact3_4an2, fact3_4a2, fact3_4bn, fact3_4b, fact3_4bn2, fact3_4b2,

szCategory,

factx_1an, factx_1a, factx_1an2, factx_1a2, factx_1bn, factx_1b, factx_1bn2, factx_1b2,
factx_2an, factx_2a, factx_2an2, factx_2a2, factx_2bn, factx_2b, factx_2bn2, factx_2b2,

seed, iFormSubmitted, szCategory, iPower, nrand, iPercent,

CGI_TARGET
    );
} //printresults10times()
